log:
  level: DEBUG

accessLog: {}

entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  smtp:
    address: :25
  smtps:
    address: :465

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${CERTBOT_EMAIL}
      storage: /certs/acme.json
      httpChallenge:
        entryPoint: web
      tlsChallenge: {}

providers:
  docker:
    exposedByDefault: false
