entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  smtp:
    address: :25
  smtps:
    address: :465

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${TLS_ACME_EMAIL}
      storage: /certs/acme.json
      tlsChallenge: {}

providers:
  file:
    filename: /etc/traefik/traefik.yml

tcp:
  routers:
    smtp-passthrough:
      entryPoints:
        - smtp
      rule: "HostSNI(`*`)"
      service: relay-smtp
    smtps-termination:
      entryPoints:
        - smtps
      rule: "HostSNI(`*`)"
      tls:
        certResolver: letsencrypt
      service: relay-smtp
  services:
    relay-smtp:
      loadBalancer:
        servers:
          - address: "relay:2525"

http:
  routers:
    relay-api-https:
      entryPoints:
        - websecure
      rule: "Host(`${RELAY_HOSTNAME}`)"
      tls:
        certResolver: letsencrypt
      service: relay-api

    relay-acme-challenge:
      entryPoints:
        - web
      rule: "Host(`${RELAY_HOSTNAME}`) && PathPrefix(`/.well-known/acme-challenge/`)"
      service: relay-api

    relay-http-redirect:
      entryPoints:
        - web
      rule: "HostRegexp(`{host:.+}`)"
      middlewares:
        - redirect-https
      service: relay-api

  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        port: 443

  services:
    relay-api:
      loadBalancer:
        servers:
          - address: "relay:3000"
