tcp:
  routers:
    smtp-passthrough:
      entryPoints:
        - smtp
      rule: "HostSNI(`*`)"
      service: relay-smtp
    smtps-termination:
      entryPoints:
        - smtps
      rule: "HostSNI(`*`)"
      tls:
        certResolver: letsencrypt
      service: relay-smtp
  services:
    relay-smtp:
      loadBalancer:
        servers:
          - address: "relay:2525"

http:
  routers:
    relay-api-https:
      entryPoints:
        - websecure
      rule: "Host(`mx1.mastel.top`)"
      tls:
        certResolver: letsencrypt
      service: relay-api

    relay-http-redirect:
      entryPoints:
        - web
      rule: "Host(`mx1.mastel.top`)"
      middlewares:
        - redirect-https
      service: relay-api

  middlewares:
    redirect-https:
      redirectScheme:
        scheme: https
        port: 443

  services:
    relay-api:
      loadBalancer:
        servers:
          - url: "http://relay:3000"
