export * from './IConfig';
export * from './IDnsLookup';
export * from './IDomain';
export * from './IEmail';
export * from './IForwarder';
export * from './IListEntry';
export * from './ILoopPrevention';
export * from './ISpamFilter';
export * from './ITenant';
